In [1]:
!pip install pandas

Requirement already satisfied: pandas in /opt/conda/lib/python3.11/site-packages (2.1.1)
Requirement already satisfied: numpy>=1.23.2 in /opt/conda/lib/python3.11/site-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import surprise

In [3]:
from surprise import SVD
from surprise.model_selection import cross_validate

In [4]:
from surprise.dataset import Dataset

In [5]:
from surprise.reader import Reader

In [6]:
load_from_df=Dataset.load_from_df

In [7]:
import pandas as pd

In [8]:
df = pd.read_csv('video_ratings.csv')

In [9]:
#hacer un df nuevo con cantidad de veces que un user se repite
df_user = df['user_id'].value_counts().reset_index()
df_user

     user_id  count
0         90     50
1        246     49
2        393     47
3        421     46
4        545     45
..       ...    ...
695      688      2
696      684      2
697      698      2
698      620      2
699      668      1

[700 rows x 2 columns]

In [10]:
#generar una variable en df_user que sea igual a 1 si count es menor o igual a 3 y 0 si es mayor que 3
df_user['mantener'] = df_user['count'].apply(lambda x: 1 if x <= 3 else 0)
df_user

     user_id  count  mantener
0         90     50         0
1        246     49         0
2        393     47         0
3        421     46         0
4        545     45         0
..       ...    ...       ...
695      688      2         1
696      684      2         1
697      698      2         1
698      620      2         1
699      668      1         1

[700 rows x 3 columns]

In [11]:
#merge df con df user 
df = pd.merge(df, df_user, on='user_id', how='left')
df

       user_id  movie_id  rating  count  mantener
0          260        63       3     34         0
1           63        18       3     29         0
2          322       131       3     38         0
3          452        84       3     24         0
4          419         3       3     41         0
...        ...       ...     ...    ...       ...
19995      282       117       3     23         0
19996      455       113       3     34         0
19997      169        11       3     39         0
19998      319       116       3     36         0
19999      325        93       3     28         0

[20000 rows x 5 columns]

In [12]:
#drop si mantener = 0
df = df[df['mantener'] == 1]
df

       user_id  movie_id  rating  count  mantener
144        659       112       3      3         1
808        627       103       3      3         1
855        693        33       3      3         1
1147       605        64       3      3         1
1585       600        84       4      2         1
1588       603        11       3      3         1
1769       631        90       3      3         1
2317       633        26       3      3         1
2524       668        77       3      1         1
2926       654        74       3      3         1
2929       620        90       3      2         1
3161       631        25       3      3         1
3221       698        98       3      2         1
3829       688       131       3      2         1
4076       693       119       3      3         1
4468       659        57       3      3         1
5009       605        48       3      3         1
5247       633        39       3      3         1
6688       684         5       3      2         1
7099       698        97       3      2         1
7490       672       102       3      3         1
8672       694        35       3      2         1
8762       659       136       3      3         1
10091      627        12       2      3         1
10400      654        69       3      3         1
11000      635       136       3      3         1
11186      654        94       3      3         1
12086      600       128       3      2         1
13213      684        13       4      2         1
13249      603         7       3      3         1
13756      693        20       3      3         1
13944      603        61       3      3         1
15726      672       137       3      3         1
16140      694        60       3      2         1
16282      631         1       3      3         1
16768      635       110       3      3         1
16904      605         7       3      3         1
17590      672       109       3      3         1
18298      688        69       3      2         1
18353      627       119       3      3         1
18731      620        37       3      2         1
18930      633       113       3      3         1
19721      635        65       3      3         1

In [13]:
df= df.drop(['mantener'], axis=1)
df

       user_id  movie_id  rating  count
144        659       112       3      3
808        627       103       3      3
855        693        33       3      3
1147       605        64       3      3
1585       600        84       4      2
1588       603        11       3      3
1769       631        90       3      3
2317       633        26       3      3
2524       668        77       3      1
2926       654        74       3      3
2929       620        90       3      2
3161       631        25       3      3
3221       698        98       3      2
3829       688       131       3      2
4076       693       119       3      3
4468       659        57       3      3
5009       605        48       3      3
5247       633        39       3      3
6688       684         5       3      2
7099       698        97       3      2
7490       672       102       3      3
8672       694        35       3      2
8762       659       136       3      3
10091      627        12       2      3
10400      654        69       3      3
11000      635       136       3      3
11186      654        94       3      3
12086      600       128       3      2
13213      684        13       4      2
13249      603         7       3      3
13756      693        20       3      3
13944      603        61       3      3
15726      672       137       3      3
16140      694        60       3      2
16282      631         1       3      3
16768      635       110       3      3
16904      605         7       3      3
17590      672       109       3      3
18298      688        69       3      2
18353      627       119       3      3
18731      620        37       3      2
18930      633       113       3      3
19721      635        65       3      3

In [14]:
df= df.drop(['count'], axis=1)
df

       user_id  movie_id  rating
144        659       112       3
808        627       103       3
855        693        33       3
1147       605        64       3
1585       600        84       4
1588       603        11       3
1769       631        90       3
2317       633        26       3
2524       668        77       3
2926       654        74       3
2929       620        90       3
3161       631        25       3
3221       698        98       3
3829       688       131       3
4076       693       119       3
4468       659        57       3
5009       605        48       3
5247       633        39       3
6688       684         5       3
7099       698        97       3
7490       672       102       3
8672       694        35       3
8762       659       136       3
10091      627        12       2
10400      654        69       3
11000      635       136       3
11186      654        94       3
12086      600       128       3
13213      684        13       4
13249      603         7       3
13756      693        20       3
13944      603        61       3
15726      672       137       3
16140      694        60       3
16282      631         1       3
16768      635       110       3
16904      605         7       3
17590      672       109       3
18298      688        69       3
18353      627       119       3
18731      620        37       3
18930      633       113       3
19721      635        65       3

In [15]:
algo = SVD()

In [16]:
df2 = pd.DataFrame()

In [17]:
df2['user'] = df['user_id'].values
df2['item'] = df['movie_id'].values
df2['rating'] = df['rating'].values

In [18]:
data_reader = Reader(line_format='user item rating')

In [19]:
data =load_from_df(df2,data_reader)

In [20]:
cross_validate(algo, data, measures=['RMSE', 'MAE'], cv=5, verbose=True)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std
RMSE (testset)    0.3326  0.1187  0.3612  0.0434  0.3571  0.2426  0.1344
MAE (testset)     0.1245  0.0824  0.1627  0.0339  0.1321  0.1071  0.0447
Fit time          0.00    0.00    0.00    0.00    0.00    0.00    0.00
Test time         0.00    0.00    0.00    0.00    0.00    0.00    0.00

{'test_rmse': array([0.33255293, 0.11869489, 0.36116979, 0.04342736, 0.35709538]),
 'test_mae': array([0.1244815 , 0.08236892, 0.16268021, 0.03389421, 0.13210926]),
 'fit_time': (0.00045299530029296875,
  0.0002703666687011719,
  0.00025272369384765625,
  0.00025963783264160156,
  0.0002627372741699219),
 'test_time': (5.8650970458984375e-05,
  2.9325485229492188e-05,
  2.956390380859375e-05,
  2.5987625122070312e-05,
  2.4557113647460938e-05)}